# Generated by Django 4.2.6 on 2024-04-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_school_database_vehicle_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='school_database',
        ),
        migrations.DeleteModel(
            name='vehicle_Data',
        ),
    ]
